Repository saito-kazumasa/equipment-management-system, pull requests merged in 2024-07, with the labels that each got.

#86 貸出申請機能を作成
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/form/CheckoutApplicationForm.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/configuration/WebSecurityConfiguration.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/CheckoutApplicationController.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/ICheckoutApplicationsMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IEquipmentsMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/ICheckoutApplicationService.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/IEquipmentService.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/impl/CheckoutApplicationService.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/impl/EquipmentService.java
  src/main/resources/static/js/checkout/checkout-application.js
  src/main/resources/templates/checkout/application/application.html
  src/main/resources/templates/checkout/application/failed.html
  src/main/resources/templates/checkout/application/success.html
Labels: enhancement

#89 ヘッダーメニューを作成
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/configuration/WebSecurityConfiguration.java
  src/main/resources/static/css/common.css
  src/main/resources/static/css/tailwind.css
  src/main/resources/static/js/header-menu.js
  src/main/resources/templates/layout.html
  src/main/resources/templates/login.html
Labels: enhancement, view

#93 checkout-application.jsをリファクタ
  src/main/resources/static/js/checkout/checkout-application.js
Labels: improvement

#92 EnumTypeHandler の final 付け忘れを修正
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/typehandler/EnumTypeHandler.java
Labels: improvement

#90 tailwindの設定を更新
  src/main/resources/static/css/tailwind.css
  tailwind.config.js
Labels: enhancement

#94 model.addAttribute() の書き方統一などのリファクタリング
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/typehandler/EnumTypeHandler.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/typehandler/JsonTypeHandler.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/configuration/MyBatisConfiguration.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/configuration/WebSecurityConfiguration.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/CheckoutApplicationController.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/IndexController.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/LoginController.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IAccountsMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/ICoursesMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IDamagedApplicationsMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IDamagedApprovalMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IEditLogsMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IEquipmentCategoriesMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IEquipmentsMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IStudentsMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/security/LoginUserDetails.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/security/LoginUserDetailsService.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/IEquipmentService.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/implement/CheckoutApplicationService.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/implement/EquipmentService.java
  src/main/resources/static/js/checkout/checkout-application.js
  src/main/resources/static/js/header-menu.js
Labels: improvement

#97 貸出申請画面を作成
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/configuration/WebSecurityConfiguration.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/IndexController.java
  src/main/resources/static/css/tailwind.css
  src/main/resources/static/js/checkout/checkout-application.js
  src/main/resources/templates/checkout/application/application.html
  src/main/resources/templates/checkout/application/failed.html
  src/main/resources/templates/checkout/application/success.html
  src/main/resources/templates/layout.html
Labels: enhancement, view

#96 ログアウト後 再度ログインすると無効なURLに飛ぶバグを修正
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/configuration/WebSecurityConfiguration.java
Labels: bug

#98 パスワードを忘れた画面の作成
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/configuration/WebSecurityConfiguration.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/PasswordResetController.java
  src/main/resources/application.properties
  src/main/resources/static/css/common.css
  src/main/resources/static/css/tailwind.css
  src/main/resources/static/js/header-menu.js
  src/main/resources/templates/layout.html
  src/main/resources/templates/login.html
  src/main/resources/templates/password_reset.html
Labels: enhancement, view

#102 damaged category の不要になった値を削除
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/constant/DamagedCategory.java
Labels: improvement

#101 フォームのラベルアニメーションを作成
  src/main/resources/static/css/tailwind.css
  src/main/resources/static/js/header-menu.js
  src/main/resources/static/js/label.js
  src/main/resources/templates/layout.html
Labels: enhancement, view

#104 Json / Object 変換機能を Util 化などのリファクタリング
  .gitignore
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/form/CheckoutApplicationForm.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/output/ErrorMessage.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/output/SuccessMessage.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/typehandler/JsonTypeHandler.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/configuration/WebSecurityConfiguration.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/LoginController.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/checkout/CheckoutApplicationController.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/checkout/CheckoutApplicationResultController.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IEquipmentsMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/ICheckoutApplicationService.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/IEquipmentService.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/checkout/IApplyCheckoutService.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/checkout/implement/ApplyCheckoutService.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/equipment/IFetchEquipmentService.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/equipment/IListEquipmentService.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/equipment/IRegisterEquipmentService.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/equipment/implement/FetchEquipmentService.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/equipment/implement/ListEquipmentService.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/equipment/implement/RegisterEquipmentService.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/service/implement/EquipmentService.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/util/JsonUtil.java
  src/main/resources/templates/checkout/application/application.html
Labels: improvement

#105 READMEを更新
  README.md
Labels: documentation

#108 ログイン後エラーになるバグを修正
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/configuration/WebSecurityConfiguration.java
Labels: bug

#110 JsonUtil を static 化
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/form/CheckoutApplicationForm.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/typehandler/JsonTypeHandler.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/util/JsonUtil.java
Labels: improvement
