Repository saito-kazumasa/equipment-management-system, pull requests merged in 2024-06, with the labels that each got.

#1 READMEを作成
  README.md
Labels: documentation

#2 プルリクのテンプレを作成
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#56 application.propertiesにDB接続情報などを追加
  src/main/resources/application.properties
Labels: enhancement

#57 Course の Mapper を作成
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/Course.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/ICourseMapper.java
Labels: enhancement

#58 プルリクテンプレを更新
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#62 プルリクテンプレ更新
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#61 貸出申請の Mapper&Entity を作成
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/CheckoutApplication.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/Course.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/ICheckoutApplicationMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/ICourseMapper.java
Labels: enhancement

#63 学生DBの Mapper&Entity を作成
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/Student.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IStudentMapper.java
Labels: enhancement

#64 貸出申請承認の Mapper&Entity を作成
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/CheckoutApproval.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/ICheckoutApprovalMapper.java
Labels: enhancement

#65 返却申請の Mapper&Entity を作成
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/ReturnApplication.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IReturnApplicationMapper.java
Labels: enhancement

#66 返却申請承認 の Mapper&Entity を作成
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/ReturnApproval.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IReturnApprovalMapper.java
Labels: enhancement

#67 アカウントDBの Mapper&Entity 作成
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/Account.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/AccountCategory.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IAccountMapper.java
Labels: enhancement

#68 破損申請の Mapper&Entity を作成
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/DamagedApplication.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/DamagedCategory.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IDamagedApplicationMapper.java
Labels: enhancement

#70 備品カテゴリDBの Mapper&Entiry を作成した
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/EquipmentCategory.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IEquipmentCategoryMapper.java
Labels: enhancement

#73 リファクタリング
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/Account.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/DamagedApplication.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/Equipment.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/StorageLocation.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/typehandler/JsonTypeHandler.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/configuration/MyBatisConfiguration.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/constant/AccountCategory.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/constant/DamagedCategory.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/constant/EquipmentState.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IAccountsMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/ICheckoutApplicationsMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/ICheckoutApprovalsMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/ICoursesMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IDamagedApplicationsMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IEditLogsMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IEquipmentCategoriesMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IEquipmentsMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IReturnApplicationsMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IReturnApprovalsMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IStorageLocationsMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IStudentsMapper.java
Labels: improvement

#74 欠陥承認の Mapper&Entity を作成
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/DamagedApproval.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IDamagedApprovalMapper.java
Labels: enhancement

#75 ログイン機能を作成
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/typehandler/EnumTypeHandler.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/typehandler/JsonTypeHandler.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/configuration/MyBatisConfiguration.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/configuration/WebSecurityConfiguration.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/IndexController.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/controller/LoginController.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IAccountsMapper.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/security/LoginUserDetails.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/security/LoginUserDetailsService.java
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
Labels: enhancement

#76 Noto Sans Serif を導入
  src/main/resources/static/css/common.css
Labels: enhancement

#77 各アイコンイメージを導入
  src/main/resources/static/images/AccountIcon.png
  src/main/resources/static/images/CameraIcon.png
  src/main/resources/static/images/ErrorIcon.png
  src/main/resources/static/images/PenIcon.png
Labels: enhancement, view

#78 Account から Salt を削除
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/Account.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/mapper/IAccountsMapper.java
Labels: enhancement

#79 tailwindcssを導入
  .gitignore
  package-lock.json
  package.json
  src/main/resources/static/css/input.css
  src/main/resources/static/css/output.css
  src/main/resources/templates/index.html
  tailwind.config.js
Labels: enhancement

#83 Equipment が SELECT できないバグを修正
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/EditLog.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/entity/JsonEquipment.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/configuration/MyBatisConfiguration.java
Labels: bug

#81 ログインページを作成
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/configuration/WebSecurityConfiguration.java
  src/main/resources/static/css/common.css
  src/main/resources/static/css/tailwind.css
  src/main/resources/templates/layout.html
  src/main/resources/templates/login.html
  tailwind.config.js
Labels: enhancement, view

#85 画像のファイル名をケバブケースに統一
  src/main/resources/static/images/account-icon.png
  src/main/resources/static/images/camera-icon.png
  src/main/resources/static/images/error-icon.png
  src/main/resources/static/images/pen-icon.png
  src/main/resources/templates/layout.html
  src/main/resources/templates/login.html
Labels: improvement

#88 メッセージ表示機能を作成
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/output/ErrorMessage.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/output/IMessage.java
  src/main/java/jp/ac/morijyobi/equipmentmanagementsystem/bean/output/SuccessMessage.java
  src/main/resources/static/css/tailwind.css
  src/main/resources/templates/layout.html
  src/main/resources/templates/login.html
  tailwind.config.js
Labels: enhancement, view

#80 ページ作成に使用するアイコンを追加
  src/main/resources/static/images/barcord-icon.png
  src/main/resources/static/images/check-icon.png
  src/main/resources/static/images/glass-icon.png
  src/main/resources/static/images/xlsxfile-icon.png
Labels: enhancement, view
